#ifndef QMLRENDERER_GLOBAL_H
#define QMLRENDERER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMLRENDERER_LIBRARY)
#  define QMLRENDERERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMLRENDERERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMLRENDERER_GLOBAL_H
